// Questions 1–10: A1–A2, 11–20: B1, 21–30: B2.
export const englishTestQuestions = [
  { q: 'Choose the correct sentence.', o: ['She are a student.', 'She is a student.', 'She am a student.', 'She be a student.'], c: 1 },
  { q: 'Complete the sentence: I ___ from Kazakhstan.', o: ['is', 'are', 'am', 'be'], c: 2 },
  { q: 'Choose the correct plural: one child, two ___.', o: ['childs', 'childes', 'child', 'children'], c: 3 },
  { q: 'Complete the sentence: My brother ___ football every Sunday.', o: ['plays', 'play', 'playing', 'is play'], c: 0 },
  { q: 'Choose the correct question: ___ you speak English?', o: ['Does', 'Are', 'Do', 'Is'], c: 2 },
  { q: 'Complete the sentence: There ___ three books on the table.', o: ['is', 'are', 'am', 'be'], c: 1 },
  { q: 'Complete the sentence: We went to the cinema ___.', o: ['tomorrow', 'every day', 'next week', 'yesterday'], c: 3 },
  { q: 'Choose the correct form: This bag is ___ than that one.', o: ['heavier', 'heavy', 'heaviest', 'more heavy'], c: 0 },
  { q: 'Complete the sentence: I have lived here ___ 2022.', o: ['for', 'since', 'during', 'from'], c: 1 },
  { q: 'Complete the sentence: If it rains tomorrow, we ___ at home.', o: ['stayed', 'staying', 'will stay', 'would stay'], c: 2 },

  { q: 'Complete the sentence: When I arrived, they ___ dinner.', o: ['have', 'were having', 'had', 'are having'], c: 1 },
  { q: 'Complete the sentence: I have never ___ to London.', o: ['went', 'go', 'been', 'being'], c: 2 },
  { q: 'Choose the correct passive sentence for “Someone built this bridge in 1990.”', o: ['This bridge was built in 1990.', 'This bridge built in 1990.', 'This bridge is building in 1990.', 'This bridge has built in 1990.'], c: 0 },
  { q: 'Complete the sentence: If I had more free time, I ___ a new language.', o: ['learn', 'will learn', 'had learned', 'would learn'], c: 3 },
  { q: 'Choose the correct reported speech: “I am tired,” Anna said.', o: ['Anna said that I am tired.', 'Anna said that she was tired.', 'Anna said that she is tired yesterday.', 'Anna said she tired.'], c: 1 },
  { q: 'Complete the sentence: I look forward to ___ from you.', o: ['hearing', 'hear', 'heard', 'have heard'], c: 0 },
  { q: 'Choose the word closest in meaning to “reliable”.', o: ['expensive', 'difficult', 'trustworthy', 'temporary'], c: 2 },
  { q: 'Complete the sentence: The meeting was postponed ___ the manager was ill.', o: ['although', 'because', 'unless', 'despite'], c: 1 },
  { q: 'Read: “Maya missed the bus, so she walked to work and arrived ten minutes late.” Why was Maya late?', o: ['She overslept.', 'She forgot her keys.', 'She was in a meeting.', 'She missed the bus.'], c: 3 },
  { q: 'Complete the sentence: You ___ have told me earlier; I could have helped.', o: ['should', 'must', 'can', 'will'], c: 0 },

  { q: 'Complete the sentence: Had I known about the delay, I ___ a different train.', o: ['take', 'will take', 'would have taken', 'had taken'], c: 2 },
  { q: 'Choose the sentence that means “Although she was inexperienced, she solved the problem.”', o: ['Despite her lack of experience, she solved the problem.', 'Because she lacked experience, she solved the problem.', 'Unless she was inexperienced, she solved the problem.', 'She solved the problem so that she was inexperienced.'], c: 0 },
  { q: 'Complete the sentence: The proposal, ___ was submitted last week, needs further revision.', o: ['who', 'where', 'whose', 'which'], c: 3 },
  { q: 'What does “mitigate the risk” mean?', o: ['Ignore the risk.', 'Reduce the possible harm.', 'Create a new risk.', 'Transfer all responsibility.'], c: 1 },
  { q: 'Complete the sentence: By the time the guests arrived, we ___ dinner.', o: ['prepare', 'have prepared', 'had prepared', 'were prepare'], c: 2 },
  { q: 'Choose the most natural formal sentence for a work email.', o: ['Send me the file now.', 'You gotta send the file.', 'Give me that file, okay?', 'Could you please send me the file by Friday?'], c: 3 },
  { q: 'Read: “The new policy aims to reduce waste; nevertheless, some staff worry it may increase costs initially.” Which statement is supported?', o: ['The policy has already reduced all costs.', 'The policy may cost more at first.', 'Staff unanimously support the policy.', 'The policy is intended to increase waste.'], c: 1 },
  { q: 'Complete the sentence: Not only ___ the deadline, but she also improved the design.', o: ['did she meet', 'she met', 'she did meet', 'met she'], c: 0 },
  { q: 'Choose the best word: The evidence is too ___ to support a firm conclusion.', o: ['compelling', 'conclusive', 'inconclusive', 'convincing'], c: 2 },
  { q: 'Read: “While remote work has improved flexibility, its effect on collaboration varies between teams.” What is the writer’s position?', o: ['Remote work always harms collaboration.', 'Remote work has no benefits.', 'All teams collaborate better remotely.', 'Its impact on collaboration depends on the team.'], c: 3 },
];
